// Generated by CoffeeScript 2.0.0-beta4
void function () {
  var module;
  module = angular.module('rocketKids.filters', []);
  module.filter('interpolate', [
    'version',
    function (version) {
      return function (text) {
        return String(text).replace(/\%VERSION\%/gm, version);
      };
    }
  ]);
}.call(this);
