// Generated by CoffeeScript 2.0.0-beta4
void function () {
  var module;
  module = angular.module('rocketKids.services', []);
  module.value('version', '0.1');
  module.factory('Student', function ($mongolabResource) {
    return $mongolabResource('students');
  });
  module.factory('Ethnicity', function ($mongolabResource) {
    return $mongolabResource('ethnicities');
  });
  module.factory('DailyComm', function ($mongolabResource) {
    return $mongolabResource('daily-communications');
  });
}.call(this);
